Sprint 3
OlegLaskov/middle.messenger.praktikum.yandex pull request #3
Opened 2022-08-19 21:16 UTC by OlegLaskov

2022-08-20 09:51 UTC, agadoev requested changes
Привет)
Есть что поправить в коде - в основном это связно со структурированием проекта и чистотой кода.
Могу посоветовать литературу, которая поможет лучше понимать что значит чистый код: 
1. Роберт Мартин "Чистый код"
2. https://www.infoq.com/presentations/Simple-Made-Easy/ очень полезный доклад

Поправь то, что сможешь и двинемся дальше

2022-08-20 09:51 UTC, agadoev commented on package.json
> +		"test": "mocha -r jsdom-global/register"
сюда стоит добавить скрипт для запуска eslint'a и stylelint'a

2022-08-20 09:51 UTC, agadoev commented on src/api/base-api.ts
> +}
Почему бы тут не использовать Interface?

2022-08-20 09:51 UTC, agadoev commented on src/api/chat-api.ts
> +	initSocket = (userId: number, chatId: number) => {
Весь функционал, относящийся к сокетам, можно вынести в utils/WebsocketTransport.ts, например, по аналогии с HTTP. сокеты в дальнейшем наверняка будут использоваться не только в chat api + сейчас ChatAPI должен хранить только бизнес логику, а сейчас он хранит и бизнес логику, и реализацию сокетов

2022-08-20 09:51 UTC, agadoev commented on src/api/chat-api.ts
> +				console.log('Получены данные=', event.data);
console.log лучше убирать из кода перед пушем. Его удобно использовать для дебага, но твоим коллегам этом может только помешать

2022-08-20 09:51 UTC, agadoev commented on src/api/chat-api.ts
> +			console.log('err='+typeof err, err);
```suggestion
			console.error('err='+typeof err, err);
```

2022-08-20 09:51 UTC, agadoev commented on src/api/chat-api.ts
> +					content+=20;
Что означает 20? Давай поместим это число в константу и дадим ей человекочитаемое название

2022-08-20 09:51 UTC, agadoev commented on src/utils/utils.ts
> +export function queryStringify(data: {[key: string]: string|number|boolean|number[]}): string {
Было бы неплохо каждую функцию вынести в отдельный файлик и одноименным названием

2022-08-20 09:51 UTC, agadoev commented on src/utils/utils.ts
> +};
Для типов я бы создал отдельный файл/папку

2022-08-20 09:51 UTC, agadoev commented on src/utils/component.ts
>  import EventBus from './event-bus';
Такие файлы как Component, Event-bus, Store, HTTP, вряд ли можно отнести к utils. Utils - это мелкий, вспомогательный функционал, который иногда требуется. Component, EventBus, Store, HTTP являются основными частями системы, на которых все строится. Я думаю, что логичнее было бы перенести их в папку core

2022-08-20 09:51 UTC, agadoev commented on src/router/router.test.ts
> +		// window.history.pushState({page: 'error404'}, 'Error 404', '/error404');
Точно ли тут нужны эти комменты? Если нет, лучше убрать их

2022-08-20 09:51 UTC, agadoev commented on src/router/router.test.ts
> +		// router.back();
Тут тоже если не нужны, лучше убрать, а если нужны - раскомментировать

2022-08-20 09:51 UTC, agadoev commented on src/utils/HOC.ts
> +export function connect(ExtComponent: typeof Component, mapStateToProps?: (state: Indexed)=>Indexed) {
Не критично, но я бы разбил этот файл. на два файла - connect.ts и saveUsertatToStore.ts

2022-08-20 09:51 UTC, agadoev commented on src/utils/HTTP.ts
> +	request = (url: string, options: RequestOptions, timeout?: number ): Promise<XMLHttpRequest> => {
timeout присутствует как в аргументах функции, так и в объекте options. Давай оставим что-то одно, чтобы устранить неопределенность

2022-08-20 09:51 UTC, agadoev commented on src/pages/ChangePassword.ts
> +	constructor(tag = 'div', props: {user?: User} = {}) {
первый аргумент tag вообще не используется. Уберем его?

2022-08-20 09:51 UTC, agadoev commented on src/pages/ChangePassword.ts
> +			];
Так будет выглядеть читаемее. И я бы вынес эти константы из функции по аналогии с тем, как ты сделал с константами для валидации

```suggestion
				const fields: Field[] = [
			{
				type: 'password',
				label: 'Старый\u00A0пароль',
				name: 'oldPassword',
				value: '',
				valid: REG_EXP.PASSWORD,
				errorMsg: ERROR_MSG.PASSWORD,
				autocomplete: 'current-password'
			},
			{
				type: 'password',
				label: 'Новый\u00A0пароль',
				name: 'newPassword',
				value: '',
				valid: REG_EXP.PASSWORD,
				errorMsg: ERROR_MSG.PASSWORD
			},
			{
				type: 'password',
				label: 'Повторите\u00A0новый\u00A0пароль',
				name: 'confirmPassword',
				value: '',
				valid: REG_EXP.PASSWORD,
				errorMsg: ERROR_MSG.CONFIRM_NEW_PASSWORD
			},
			{
				type: 'hidden',
				name: 'login',
				value: props?.user?.login,
				autocomplete: 'login'
			},
		];
```

2022-08-20 09:51 UTC, agadoev commented on src/pages/ChangePassword.ts
> +					inputArr[2].element).value;
Такое чтение по индексу выглядит довольно небезопасным

2022-08-20 09:51 UTC, agadoev commented on src/pages/ChangePassword.ts
> +				);
Тут проблема в том, что если изменить строку 'hidden' или 'div', то typescript не выдаст ошибку и эту ошибку придется долго искать самому. Typescript становится полезным тогда, когда помогает нам определять ошибки до момента запуска программы. Я бы тут типизировал tag и второй аргумент LineInput. Благо, в TS есть замечательный union type, который позволяет это делать для строк.


``` TElementType = 'hidden' | 'visible' | etc. ```

2022-08-20 09:51 UTC, agadoev commented on src/pages/ChatPage.ts
> +								chatId = this.children?.chatPage?.children?.main?.props?.chatInfo?.id;
если в коде такая глубокая вложенность объектов, скорее всего надо разбивать большие глубокие объекты на маленькие неглубокие.

2022-08-20 09:51 UTC, agadoev commented on src/pages/ChatPage.ts
> +			}
Вот тут не очень понял. Если mode: boolean, то есть всего 2 пути.
```suggestion
			if(!mode){
			    modalAddUser.hide();
			    return;
			}
			   modalAddUser.show()
		           modalAddUser.isShow ? modalAddUser.hide() : modalAddUser.show();
			}
```

2022-08-21 22:23 UTC, OlegLaskov commented on src/pages/ChatPage.ts
> +			}
Там был вариант с underfined. Но я это потом переделал. Я исправил. Убрал лишнее

2022-08-21 22:24 UTC, OlegLaskov commented on src/pages/ChangePassword.ts
> +				);
Исправил

2022-08-21 22:24 UTC, OlegLaskov commented on src/pages/ChangePassword.ts
> +			];
Исправил

2022-08-21 22:25 UTC, OlegLaskov commented on src/api/chat-api.ts
> +				console.log('Получены данные=', event.data);
Исправил

2022-08-21 22:26 UTC, OlegLaskov commented on src/api/chat-api.ts
> +	initSocket = (userId: number, chatId: number) => {
Исправил

2022-08-21 22:26 UTC, OlegLaskov commented on src/api/base-api.ts
> +}
Сделал

2022-08-21 22:26 UTC, OlegLaskov commented on package.json
> +		"test": "mocha -r jsdom-global/register"
Добавил

2022-08-21 22:27 UTC, OlegLaskov commented on src/api/chat-api.ts
> +					content+=20;
Исправил

2022-08-21 22:27 UTC, OlegLaskov commented on src/utils/utils.ts
> +};
Сделал

2022-08-21 22:27 UTC, OlegLaskov commented on src/utils/component.ts
>  import EventBus from './event-bus';
Перенес

2022-08-21 22:28 UTC, OlegLaskov commented on src/router/router.test.ts
> +		// window.history.pushState({page: 'error404'}, 'Error 404', '/error404');
Убрал

2022-08-21 22:29 UTC, OlegLaskov commented on src/router/router.test.ts
> +		// router.back();
Убрал. Хотел спросить совета: как тестировать роутер? Можете дать пример?

2022-08-21 22:29 UTC, OlegLaskov commented on src/utils/HTTP.ts
> +	request = (url: string, options: RequestOptions, timeout?: number ): Promise<XMLHttpRequest> => {
Исправил

2022-08-21 22:29 UTC, OlegLaskov commented on src/pages/ChangePassword.ts
> +	constructor(tag = 'div', props: {user?: User} = {}) {
Убрал

2022-08-21 22:31 UTC, OlegLaskov commented on src/pages/ChangePassword.ts
> +					inputArr[2].element).value;
Не могу найти здесь другого решения. Можешь подсказать?

2022-08-21 22:31 UTC, OlegLaskov commented on src/pages/ChatPage.ts
> +								chatId = this.children?.chatPage?.children?.main?.props?.chatInfo?.id;
Не могу найти здесь другого решения. Можешь подсказать?

2022-08-23 15:24 UTC, agadoev requested changes
Привет)
Прости за задержку, слак в последнее время лагает и мне не приходили уведомления о том, что работа готова. Я ответил на твои вопросы и нашел еще несколько моментов, которые нужно будет скорее всего поправить, они небольшие. По поводу тестов - их можно делать в 4 спринте, но так или иначе делать придется, поэтому можешь сделать их сейчас. Если хочешь - сделай в 4-ом. По тестированию есть хорошая [книга](https://www.ozon.ru/product/ekstremalnoe-programmirovanie-razrabotka-cherez-testirovanie-140489225/?sh=8nVReyKPeg)

Обучение - процесс итеративный, но с каждый итерацией код становится лучше :)

2022-08-23 15:24 UTC, agadoev commented on src/pages/ChangePassword.ts
> +					inputArr[2].element).value;
Хорошо. Например, я бы отказался от использования массива fields, и вместо этого сделал бы 4 переменных, например так:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/37894659/186188312-38bf50cd-04a0-47d8-af37-9e89a705bfca.png">
У такого подходя есть ряд преимуществ:
1) Нам не нужно использовать индексы и помнить какой индекс на какое поле указывается
2) Код сильно упрощается, потому что нам не нужно больше пробегаться по массиву и через индексы и сложные if-els'ы определять какое поле мы обрабатываем

2022-08-23 15:24 UTC, agadoev commented on src/pages/ChangePassword.ts
> +					valid: REG_EXP.PASSWORD,
как насчет переименовать это поле? сейчас при чтении кода кажется, что в нем хранится либо boolean переменная, либо функция, возвращающая boolean переменную, хотя на самом деле там режит regexp. Предлагаю назвать ее так:
```suggestion
					validationRegexp: REG_EXP.PASSWORD, 
```

2022-08-23 15:24 UTC, agadoev commented on src/pages/ChangePassword.ts
> +			const fieldvalid = (name==='confirm_password') ? ()=>(
Сразу почему-то не обратил внимание на именование переменных. Хорошим тоном считается использование одного стиля именования, например pascalCase
```suggestion
			const lineInput: FieldBlock = {label, input: inputArr[i]};
	
			const fieldValid = (name==='confirm_password') ? ()=>(
```

2022-08-23 15:24 UTC, agadoev commented on src/pages/ChangePassword.ts
> +						console.log('resp='+typeof resp, resp);
Лишний console.log

2022-08-23 15:24 UTC, agadoev commented on src/pages/ChangePassword.ts
> +		const link = null;
Зачем тут этот link? Может его стоит убрать и инициализировать в конструкторе ProfileForm?

2022-08-23 15:24 UTC, agadoev commented on src/pages/ChatPage.ts
> +								chatId = this.children?.chatPage?.children?.main?.props?.chatInfo?.id;
1) Можно хранить не только ссылку на children, а на children, main. И тогда читать придется только из main.props.chatInfo.id
2) Решение получше, можно хранить chatId в store и читать его напрямую от туда

2022-08-23 15:24 UTC, agadoev commented on src/pages/ChatPage.ts
> +								chatId = this.children?.chatPage?.children?.main?.props?.chatInfo?.id;
В данном конкретном случае возможно действительно сложно будет этот кусок распутать. Можешь сейчас оставить как есть, просто знай на всякий случай, что такие длинные цепочки лучше не использовать. Такие конструкции довольно хрупкие и если где-то в читаемых свойствах лежит null или undefined, все рухнет

2022-08-23 15:24 UTC, agadoev commented on src/router/router.test.ts
> +		// router.back();
Вот тут неплохой пример
https://github.com/EkaterinaGulevich/middle.messenger.praktikum.yandex/blob/sprint_4/src/core/tests/router.test.ts

На что стоит обратить внимание:
1) В тестах имитируется dom дерево с помощью jsdom 
2) Создаются заглушки компонентов

Чего тут нет, но неплохо было бы дописать:
1) тестирование для back()
2) тестирование для forward()

2022-08-23 19:01 UTC, OlegLaskov commented on src/pages/ChangePassword.ts
> +					inputArr[2].element).value;
Исправил

2022-08-23 19:02 UTC, OlegLaskov commented on src/pages/ChatPage.ts
> +								chatId = this.children?.chatPage?.children?.main?.props?.chatInfo?.id;
Ок!

2022-08-23 19:03 UTC, OlegLaskov commented on src/pages/ChangePassword.ts
> +					valid: REG_EXP.PASSWORD,
Исправил

2022-08-23 19:03 UTC, OlegLaskov commented on src/pages/ChangePassword.ts
> +			const fieldvalid = (name==='confirm_password') ? ()=>(
Исправил

2022-08-23 19:03 UTC, OlegLaskov commented on src/pages/ChangePassword.ts
> +						console.log('resp='+typeof resp, resp);
Удалил

2022-08-23 19:04 UTC, OlegLaskov commented on src/pages/ChangePassword.ts
> +		const link = null;
Удалил

2022-08-23 22:29 UTC, OlegLaskov commented on src/router/router.test.ts
> +		// router.back();
Добавил тесты для back() и forward()

2022-08-24 05:45 UTC, agadoev approved these changes
Привет, Олег)
Спасибо за твое терпение и все правки, которые ты сделал. Код стал лучше.
Работу принимаю, удачи в четвертом спринте :)

2022-10-29 15:41 UTC, merged