Sprint 4
OlegLaskov/middle.messenger.praktikum.yandex pull request #4
Opened 2022-11-13 00:52 UTC by OlegLaskov

2022-11-13 16:13 UTC, maks88sgt requested changes
Здравствуйте. Работу пока принять не могу, потому что не выполнен ряд ключевых требований:
1. Не настроен прекоммит хук.
2. Аудит зависимостей выдает ошибки 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/49103217/201531442-c52bd7c2-3688-4ad0-be2b-fb4f6ccf6f16.png">
3. Проект не проходит автоматические проверки. https://github.com/OlegLaskov/middle.messenger.praktikum.yandex/actions/runs/3455640947/jobs/5767807917
4. Локальная дев сборка не работает (при запуске приложение выдает ошибку).
5. Тесты для проекта написаны, но оне не в этом пулл реквесте. Нужно объединить все эти изменения в один ПР.
Чтобы идти дальше необходимо закрыть эти требования.

2022-11-13 16:13 UTC, maks88sgt commented on src/components/list/index.ts
>  }
Здесь гит ругается на отсутствие окончания файла. Вот тут можно почитать что это https://moviecultists.com/when-to-use-eof. Лучше всего настроить ИДЕ, чтобы это проставлялось автоматически.

2022-11-13 16:13 UTC, maks88sgt commented on server.js
> +	res.sendFile(path.join(__dirname, 'index.html'));
Для корректной работы сервера достаточно `app.use(express.static(__dirname ));` остальной код не имеет особого смысла

2022-11-14 18:31 UTC, OlegLaskov commented on server.js
> +	res.sendFile(path.join(__dirname, 'index.html'));
Я попробовал удалить остальное - не работает. Что ты имеешь ввиду?

2022-11-14 18:35 UTC, OlegLaskov commented on src/components/list/index.ts
>  }
Не вижу, в каком месте он ругается? У меня не ругается.
По поводу тестов: я учился в 15 когорте и у меня их приняли в 3-м спринте.
Зачем мне объединять пул-реквесты?
Ты будешь заново проверять весь третий спринт?

2022-11-15 05:17 UTC, maks88sgt commented on server.js
> +	res.sendFile(path.join(__dirname, 'index.html'));
Ну например, отдавать страницу при получении сервером POST запроса это точно неправильно.

2022-11-15 05:20 UTC, maks88sgt commented on src/components/list/index.ts
>  }
Вот здесь ругается
<img width="670" alt="image" src="https://user-images.githubusercontent.com/49103217/201832761-2988e1f6-d6c7-4ec5-937a-58b1945ffb7d.png">

2022-11-15 05:34 UTC, maks88sgt approved these changes
Отличная работа. Удачи на курсе!

2022-11-15 07:35 UTC, OlegLaskov commented
Спасибо!

2022-11-18 14:46 UTC, merged